
package com.iklimsa.services.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2.9
 * 
 */
@XmlRootElement(name = "BusinessException", namespace = "http://services.iklimsa.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BusinessException", namespace = "http://services.iklimsa.com/", propOrder = {
    "faultDetail",
    "message"
})
public class BusinessExceptionBean {

    private com.iklimsa.exceptions.BusinessExceptionDetail faultDetail;
    private String message;

    /**
     * 
     * @return
     *     returns BusinessExceptionDetail
     */
    public com.iklimsa.exceptions.BusinessExceptionDetail getFaultDetail() {
        return this.faultDetail;
    }

    /**
     * 
     * @param faultDetail
     *     the value for the faultDetail property
     */
    public void setFaultDetail(com.iklimsa.exceptions.BusinessExceptionDetail faultDetail) {
        this.faultDetail = faultDetail;
    }

    /**
     * 
     * @return
     *     returns String
     */
    public String getMessage() {
        return this.message;
    }

    /**
     * 
     * @param message
     *     the value for the message property
     */
    public void setMessage(String message) {
        this.message = message;
    }

}
